### ISSUE TITLE
Where does expert_c_latent.npy come from？

### ISSUE THREAD

**Issue by freedomsb** [SSRheart/TSFlow#2]
I appreciate your work, and would like to ask a question is：
How the expert_c_latent.npy used in the testing phase is calculated? 
I looked at the training code and didn't find the code to save expert_c_latent.npy

**Comment by freedomsb** [comment]
According to my understanding, the input of this z should be a random Gaussian distribution?

**Comment by SSRheart** [comment]
The input of this z is sampled from random Gaussian distribution. Thus, different z can generate different retouching styles. 
In the testing phase, we first obtain the latent z by reversing TSFlow and the tone style representation in the training set. The expert_c_latent can be calculated by formula (13) in the paper.

**Comment by freedomsb** [comment]
Woooow，thank you for such a quick reply. I'll check it out. 
By the way, if it's convenient，which function in this code is used to calculate this latent.npy?

**Comment by freedomsb** [comment]
I seem to understand, thank you for your answer, this Z is the average of the trained model running the training set again, it should be easy to implement~
